spring.application.name: 'imageliteapi'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: postgress
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
